//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.17 at 06:03:51 PM CEST 
//


package org.jboss.bus.config.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jboss.bus.config.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jboss.bus.config.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Federated }
     * 
     */
    public Federated createFederated() {
        return new Federated();
    }

    /**
     * Create an instance of {@link Federated.Bus }
     * 
     */
    public Federated.Bus createFederatedBus() {
        return new Federated.Bus();
    }

    /**
     * Create an instance of {@link Federated.Bus.Translators }
     * 
     */
    public Federated.Bus.Translators createFederatedBusTranslators() {
        return new Federated.Bus.Translators();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link Federated.Bus.Translators.Translator }
     * 
     */
    public Federated.Bus.Translators.Translator createFederatedBusTranslatorsTranslator() {
        return new Federated.Bus.Translators.Translator();
    }

}
